
name: Build and Test LAWLINK

on:
  push:
    branches: [ griffin2 , master ]
  pull_request:
    branches: [ griffin2 , master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code
      - name: https://github.com/Celestialsteel/Lawlink-OOP.git
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies (optional but recommended)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build with Maven
      - name: Build and Test with Maven
        run: mvn clean install
